# Generated by Django 4.2.7 on 2023-12-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OqituvchiKategoriyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=455)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MeyoriyXujjatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=455)),
                ('fayl', models.FileField(upload_to='meyoriy-xujjatlar')),
                ('kategoriyasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='more_app.oqituvchikategoriyalari')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
