# Generated by Django 4.2.7 on 2023-12-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meyoriyxujjatlar',
            name='yuklashlar_soni',
            field=models.BigIntegerField(default=0),
        ),
    ]
