# Generated by Django 4.2.7 on 2023-12-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more_app', '0002_meyoriyxujjatlar_yuklashlar_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='oqituvchikategoriyalari',
            name='orqa_fon',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
    ]
