# Generated by Django 4.2.7 on 2023-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-me')),
                ('title', models.CharField(max_length=255)),
                ('manzil_title', models.CharField(max_length=255)),
                ('manzil_body', models.CharField(max_length=255)),
                ('phone_title', models.CharField(max_length=255)),
                ('phone_body', models.CharField(max_length=255)),
                ('email_title', models.CharField(max_length=255)),
                ('email_body', models.CharField(max_length=255)),
                ('map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
