# Generated by Django 4.2.7 on 2023-12-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_alter_aboutme_options_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='phone',
            new_name='tg_username',
        ),
    ]
