# Generated by Django 4.2.7 on 2023-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=255)),
                ('cap_title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('app_store_title', models.CharField(max_length=255)),
                ('app_store_link', models.CharField(max_length=255)),
                ('google_play_title', models.CharField(max_length=255)),
                ('google_play_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMavjudYonalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('cap_title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('letter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMehnatFaoliyatiDivs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMehnatFaoliyatim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWelcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeYonalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeYonalishlarDivs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
