# Generated by Django 4.2.7 on 2023-11-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeyonalishlardivs',
            name='svg',
            field=models.FileField(upload_to='svglar'),
        ),
    ]
