# Generated by Django 4.2.7 on 2023-12-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_amaliy_testlar_alter_maruza_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaliy',
            name='yuklashlar_soni',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maruza',
            name='yuklashlar_soni',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slayd',
            name='yuklashlar_soni',
            field=models.BigIntegerField(default=0),
        ),
    ]
